### ISSUE TITLE
Ambiguous phrasing re: scuttling.

### ISSUE THREAD

**Issue by gpallis** [shmup/card-game-rules#1]
The rules state that you can scuttle things that are exceed in value, so that 8C can scuttle 7H but not 8H. However, since "exceed" is ambiguous, I think that an example should make clear that 8H _can_ scuttle 8C.

**Comment by shmup** [comment]
But the 8H cannot scuttle the 8C.

The 8S can scuttle the 8C, though.

Do you have a suggestion on a preferred wording?

**Comment by gpallis** [comment]
> But the 8H cannot scuttle the 8C.

I'm a little confused - why not? Hearts are higher than clubs.

**Comment by shmup** [comment]
YEP, I definitely said that wrong haha.

I'll work on wording.

**Comment by shmup** [comment]
Heh finally fixed this, thanks @gpallis -> #https://github.com/shmup/card-game-rules/commit/1d67b253db605f10365c5dad03a05bf9d3e5c38b
